### ISSUE TITLE
No longer connects to  Yahoo mail.

### ISSUE THREAD

**Issue by lobo012847** [Cobote/share-link-via-email#10]
Does not connect. Worked fine for several months now nothing.

**Comment by Cobote** [comment]
What is the URL that is created?

**Comment by lobo012847** [comment]
http://compose.mail.yahoo.com/?to=&subject=(485%20unread)%20-%20Yahoo%20-%20Yahoo%20Mail&body=https%3A%2F%2Fmg.mail.yahoo.com%2Fneo%2Flaunch%3F.rand%3Dcn6k6rjj2ojin%23745404077

I have already uninstalled and reinstalled

**Comment by Cobote** [comment]
Are you signed in? What happens with this link? http://compose.mail.yahoo.com

**Comment by lobo012847** [comment]
This works fine. Thanks for your assistance. I uninstalled and reinstalled and it now works fine. 


 "To grow old is  mandatory. To grow up is  optional."
