### ISSUE TITLE
Problem with Share link via email

### ISSUE THREAD

**Issue by bbildman** [Cobote/share-link-via-email#6]
Hi, not sure this is an extension issue, but my Windows live mail was acting funny, so I updated it. Before the update, I used your extension share link by email for a year (Opera browser) now and it has worked flawlessly. However since the WLM update, when I click on the right clicked "Send page by email" a new Opera 34 tab opens and then nothing, the address in the new tab is:

mailto:?Subject=Ultimate%20Outsider%3A%20Using%20GWX%20Control%20Panel%20(formerly%20GWX%20Stopper)%20to%20Permanently%20Remove%20the%20%27Get%20Windows%2010%27%20Icon&body=http%3A%2F%2Fblog.ultimateoutsider.com%2F2015%2F08%2Fusing-gwx-stopper-to-permanently-remove.html

Can you help me??

**Comment by Cobote** [comment]
This is a Chrome only extension. Please find the correct support site for your issue.
